### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mike-011#1]
Enable 2FA:
* [x] proceed at https://github.com/settings/security
* [x] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US

**Comment by mike-011** [comment]
2FA and MFA - is not convenient for me. But if is it mandatory requirement - i will do it.

**Comment by webknjaz** [comment]
Yes, it's mandatory to ensure that you get used to using SSH.

**Comment by mike-011** [comment]
done
