### ISSUE TITLE
Install and configure an operating system of the GNU/Linux family

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mike-011#2]
Overview
========

In order to have a superior development environment, you need to set up and configure appropriate software yourself. You also need to know how to configure things, where they are in your system, and how to survive in that scary black thing with white letters in it — The Terminal.

![](https://academy.avast.com/hubfs/New_Avast_Academy/Hackers/Hacker-Hero.png)

Let's start by setting up an operating system of the [GNU/Linux OS family] (that is based on [a kernel called Linux]).
Now, you have two options: use [Fedora] **(recommended)** or some flavor of Ubuntu (like XUbuntu, frequently used by beginners).
It's best to install it directly on your hardware (as a dual-boot, if needed) but you can also try it out in a VM (like [VirtualBox]).
You also choose to stay on macOS if absolutely necessary but you'll still have to learn your way around terminal-based approaches.

The objective of this task is to get familiar with command-line tools and learn to set up software without using any of the GUI software.

Fedora
------
* [ ] Install [Fedora][download Fedora]
* [ ] Learn about DNF/YUM/RPM. [Here][DNF] and [there][RPM]. Also: https://fedoramagazine.org/rpm-packages-explained/.
* [ ] [optionally] Add RPM Fusion to your system: https://rpmfusion.org/
* [ ] Install [Kitty terminal emulator][install Kitty on RPM]
* [ ] [Install Google Chrome][install Google Chrome on RPM]. No GUI-based install, please.
* [ ] Install [Git]
* [ ] Install VS Code using [this instruction][install VS Code on RPM], **but** without downloading `*.rpm` file from browser.

Ubuntu
------
* [x] Install [XUbuntu]
* [x] Learn about APT. [Here][APT] and [there][APT How To]
* [x] Install [Kitty terminal emulator][install Kitty on Deb]
* [x] [Install Google Chrome][install Google Chrome on Deb] but scroll to the section `"Install Google Chrome on Ubuntu 18.04 LTS from the Command Line"` and use it. No GUI-based install, please.
* [x] Install [Git from PPA][Git]
* [x] Install VS Code using [this instruction][install VS Code on Deb], **but** without downloading `*.deb` file so find the line `"The repository and key can also be installed manually with the following script:"` and go from there

[a kernel called Linux]: https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri
[APT]: https://help.ubuntu.com/lts/serverguide/apt.html.en
[APT How To]: https://help.ubuntu.com/community/AptGet/Howto
[DNF]: https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/package-management/DNF/
[download Fedora]: https://getfedora.org/en/workstation/download/
[Fedora]: https://getfedora.org/
[Git]: https://git-scm.com/download/linux
[GNU/Linux OS family]: https://www.quora.com/Is-Linux-an-operating-system-or-a-kernel/answer/Hary-Irfantri
[install Google Chrome on Deb]: https://www.linuxbabe.com/ubuntu/install-google-chrome-ubuntu-18-04-lts
[install Google Chrome on RPM]: https://www.if-not-true-then-false.com/2010/install-google-chrome-with-yum-on-fedora-red-hat-rhel/
[install Kitty on Deb]: https://sw.kovidgoyal.net/kitty/binary.html
[install Kitty on RPM]: https://copr.fedorainfracloud.org/coprs/gagbo/kitty-latest/
[install VS Code on Deb]: https://code.visualstudio.com/docs/setup/linux#_installation
[install VS Code on RPM]: https://code.visualstudio.com/docs/setup/linux#_rhel-fedora-and-centos-based-distributions
[RPM]: https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/RPM/
[VirtualBox]: https://www.virtualbox.org/
[XUbuntu]: https://xubuntu.org/

**Comment by mike-011** [comment]
I have  Lubuntu 18.04.5 LTS
