### ISSUE TITLE
Create an SSH key and add it to GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mike-011#3]
See:
* https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key (you may omit adding a password)
* https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

After completing instructions, post the result of the following command in a comment to this issue:
```shell
ssh -T git@github.com
```

Check yourself
--------------

If performed correctly, you'll see your GitHub username in the console output.

**Comment by mike-011** [comment]
done
