### ISSUE TITLE
Create an empty commit on master (and push *nothing* else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-mike-011#5]
```console
git commit --allow-empty -m 'Initial commit'
git push origin master
```

And report here after that.

**Comment by mike-011** [comment]
done

**Comment by webknjaz** [comment]
Perfect! I've applied branch protection to master. From now on, you'll work with branches and PRs whenever you need to send code for review. The details will follow in the respective issues.
